#!/usr/bin/env python3
"""Calendar support for the Spider-Man assistant, via Evolution Data Server.

Why not the Google Calendar API? calendar.readonly is a "sensitive" scope that
Google refuses for unverified apps, and a Workspace admin can disable the secret
iCal address. Instead the account is added once in GNOME Settings → Online
Accounts (GNOME's OAuth client is verified and trusted), GNOME syncs the
calendar into Evolution Data Server, and we read that local cache. No network
calls, no tokens of our own, nothing shared publicly.

Reads ~/.cache/evolution/calendar/*/cache.db (read-only) and expands recurring
events into concrete occurrences.

Commands:
    calendars   list detected calendars
    events      list upcoming events
    sync        merge upcoming events into tasks.json
    seen <id>   record an event as announced (called by the overlay)
    show        show settings
"""
import json, os, re, sys, glob, sqlite3
from pathlib import Path
from datetime import datetime, timedelta, timezone

CONF       = Path.home() / ".config" / "spiderman"
CAL_CONF   = CONF / "calendar.json"
TASKS_FILE = CONF / "tasks.json"
SEEN_FILE  = CONF / "gcal_seen.json"
EDS_GLOB   = str(Path.home() / ".cache/evolution/calendar/*/cache.db")

LOOKAHEAD_H  = 24     # how far ahead to look
LEAD_MINUTES = 10     # announce this many minutes before an event starts
REFRESH_MINUTES = 5   # how often Evolution should poll Google for changes
SKIP_ALLDAY  = True   # all-day entries (holidays, birthdays) have no useful time

try:
    import icalendar
    import recurring_ical_events
except ImportError as e:
    print(f"❌ missing library: {e}", file=sys.stderr)
    print("   Run: cd ~/spider-asst && .venv/bin/pip install "
          "icalendar recurring-ical-events", file=sys.stderr)
    sys.exit(2)


# ---------------------------------------------------------------- storage
def _read(p, default):
    try:
        return json.loads(p.read_text())
    except Exception:
        return default

def load_conf():   return _read(CAL_CONF, {})
def load_tasks():  return _read(TASKS_FILE, [])
def save_tasks(t): TASKS_FILE.write_text(json.dumps(t, indent=2))
def load_seen():   return _read(SEEN_FILE, {})

def save_conf(d):
    CONF.mkdir(parents=True, exist_ok=True)
    CAL_CONF.write_text(json.dumps(d, indent=2))

def save_seen(d):
    cutoff = datetime.now().timestamp() - 86400          # prune after a day
    d = {k: v for k, v in d.items() if v > cutoff}
    SEEN_FILE.write_text(json.dumps(d, indent=2))


# ---------------------------------------------------------------- EDS reading
def find_caches():
    """Every Evolution calendar cache, newest-modified first."""
    return sorted(glob.glob(EDS_GLOB), key=os.path.getmtime, reverse=True)


def request_refresh():
    """Ask Evolution to re-sync its online accounts.

    GNOME refreshes calendars on a ~30 minute cycle, so a just-created event
    can be missing from the local cache. This nudges it. Best-effort and
    non-blocking: the sync proceeds with whatever is cached regardless.
    """
    import subprocess
    try:
        out = subprocess.run(
            ["gdbus", "introspect", "--session",
             "--dest", "org.gnome.evolution.dataserver.Sources5",
             "--object-path", "/org/gnome/evolution/dataserver/SourceManager",
             "--recurse"], capture_output=True, text=True, timeout=10).stdout
    except Exception:
        return
    # collection sources (accounts) are the ones RefreshBackend accepts
    for uid in set(re.findall(r"readonly s UID = '([0-9a-f]{40})'", out)):
        blk = out.split(f"'{uid}'")[0][-3000:]
        if "[Collection]" not in blk:
            continue
        try:
            subprocess.run(
                ["gdbus", "call", "--session",
                 "--dest", "org.gnome.evolution.dataserver.Sources5",
                 "--object-path", "/org/gnome/evolution/dataserver/SourceManager",
                 "--method",
                 "org.gnome.evolution.dataserver.SourceManager.RefreshBackend",
                 uid], capture_output=True, timeout=10)
        except Exception:
            pass


def ensure_refresh_interval(minutes=REFRESH_MINUTES):
    """Keep Evolution polling the calendars every `minutes`.

    GNOME defaults to 30 minutes, which is too slow for event reminders. The
    source is generated by GNOME Online Accounts and lives only in EDS's
    runtime store, so it can be regenerated (and reset) after a reboot — hence
    we re-assert it on every sync rather than setting it once.
    """
    try:
        import gi
        gi.require_version("Gio", "2.0")
        from gi.repository import Gio, GLib
    except Exception:
        return
    try:
        bus = Gio.bus_get_sync(Gio.BusType.SESSION, None)
        res = bus.call_sync("org.gnome.evolution.dataserver.Sources5",
                            "/org/gnome/evolution/dataserver/SourceManager",
                            "org.freedesktop.DBus.ObjectManager",
                            "GetManagedObjects", None, None,
                            Gio.DBusCallFlags.NONE, 5000, None)
    except Exception:
        return
    excluded = set(load_conf().get("exclude", []))
    want = f"IntervalMinutes={minutes}"
    for path, ifaces in res.unpack()[0].items():
        src = ifaces.get("org.gnome.evolution.dataserver.Source")
        if not src:
            continue
        data, uid = src.get("Data", ""), src.get("UID", "")
        # only online calendars we actually read
        if "[Calendar]" not in data or "BackendName=caldav" not in data:
            continue
        if uid in excluded or want in data:
            continue
        new = re.sub(r"IntervalMinutes=\d+", want, data)
        if new == data:
            continue
        try:
            bus.call_sync("org.gnome.evolution.dataserver.Sources5", path,
                          "org.gnome.evolution.dataserver.Source.Writable",
                          "Write", GLib.Variant("(s)", (new,)), None,
                          Gio.DBusCallFlags.NONE, 8000, None)
        except Exception:
            pass


def cache_label(db):
    """A human-ish name for a cache, from its first few event summaries."""
    try:
        con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
        n = con.execute("SELECT COUNT(*) FROM ECacheObjects").fetchone()[0]
        sample = []
        for (obj,) in con.execute("SELECT ECacheOBJ FROM ECacheObjects LIMIT 3"):
            m = re.search(r"^SUMMARY[^:]*:(.*)$", obj or "", re.M)
            if m:
                sample.append(m.group(1).strip()[:26])
        con.close()
        return n, sample
    except Exception:
        return 0, []


def _calendar_from_cache(db):
    """Build one VCALENDAR containing every VEVENT in this cache."""
    cal = icalendar.Calendar()
    cal.add("prodid", "-//spider-asst//EN")
    cal.add("version", "2.0")
    try:
        con = sqlite3.connect(f"file:{db}?mode=ro", uri=True)
        rows = con.execute("SELECT ECacheOBJ FROM ECacheObjects").fetchall()
        con.close()
    except Exception:
        return None
    added = 0
    for (obj,) in rows:
        if not obj or "BEGIN:VEVENT" not in obj:
            continue
        try:
            wrapped = ("BEGIN:VCALENDAR\nVERSION:2.0\nPRODID:-//x//\n"
                       + obj.strip() + "\nEND:VCALENDAR")
            for comp in icalendar.Calendar.from_ical(wrapped).walk("VEVENT"):
                cal.add_component(comp)
                added += 1
        except Exception:
            continue          # one malformed event must not kill the sync
    return cal if added else None


def fetch_events():
    """Return (events, error). Each event: {id, title, start(epoch), calendar}."""
    caches = find_caches()
    if not caches:
        return None, ("no calendars found — add your account in "
                      "Settings → Online Accounts (enable Calendar)")
    excluded = set(load_conf().get("exclude", []))
    now = datetime.now(timezone.utc)
    end = now + timedelta(hours=LOOKAHEAD_H)
    out = []
    for db in caches:
        key = Path(db).parent.name
        if key in excluded:
            continue
        cal = _calendar_from_cache(db)
        if cal is None:
            continue
        try:
            occurrences = recurring_ical_events.of(cal).between(now, end)
        except Exception:
            continue
        for ev in occurrences:
            start = ev.get("DTSTART")
            if start is None:
                continue
            dt = start.dt
            if not isinstance(dt, datetime):
                if SKIP_ALLDAY:
                    continue
                dt = datetime(dt.year, dt.month, dt.day, 9, 0)
            if dt.tzinfo is None:
                dt = dt.astimezone()
            if str(ev.get("STATUS", "")).upper() == "CANCELLED":
                continue
            uid = str(ev.get("UID", ""))
            out.append({
                "id":       f"{uid}@{int(dt.timestamp())}",   # per-occurrence
                "title":    str(ev.get("SUMMARY", "(no title)")),
                "start":    dt.timestamp(),
                "calendar": key[:8],
            })
    # a shared UID can appear in two caches; keep one per occurrence
    dedup = {e["id"]: e for e in out}
    events = sorted(dedup.values(), key=lambda e: e["start"])
    return events, None


def pull():
    """Add upcoming events to tasks.json, due LEAD_MINUTES before they start."""
    events, err = fetch_events()
    if err:
        return {"error": err}
    seen = load_seen()
    tasks = load_tasks()
    have = {t["gid"] for t in tasks if t.get("gid")}
    next_id = max([t.get("id", 0) for t in tasks], default=0) + 1
    now = datetime.now().timestamp()
    added = 0
    for ev in events:
        gid = "cal:" + ev["id"]
        if gid in have or gid in seen:
            continue
        # Announce LEAD_MINUTES early — but if we only learned about the event
        # after that window (GNOME refreshes on a ~30 min cycle), still announce
        # immediately rather than staying silent. Only genuinely-started events
        # are skipped.
        if ev["start"] <= now:
            continue
        due = max(ev["start"] - LEAD_MINUTES * 60, now)
        at = datetime.fromtimestamp(ev["start"]).strftime("%H:%M")
        tasks.append({"id": next_id, "type": "event",
                      "text": f"{ev['title']} at {at}",
                      "due": due, "fired": False,
                      "source": "eds", "gid": gid,
                      "estart": ev["start"]})
        next_id += 1
        added += 1
    if added:
        save_tasks(tasks)
    return {"added": added, "events": len(events)}


# ---------------------------------------------------------------- commands
def cmd_calendars(args=()):
    caches = find_caches()
    if not caches:
        print("📅 No Evolution calendars found.")
        print("   Add your account: Settings → Online Accounts → Google (enable Calendar)")
        return 1
    excluded = set(load_conf().get("exclude", []))
    print(f"📅 {len(caches)} calendar cache(s):")
    for db in caches:
        key = Path(db).parent.name
        n, sample = cache_label(db)
        mark = "🚫 excluded" if key in excluded else "✅ included"
        print(f"   {key[:8]}  {n:>4} object(s)  {mark}")
        for s in sample:
            print(f"            • {s}")
    print("\n   exclude one with:  spiderman calendar exclude <id>")
    return 0


def cmd_exclude(args):
    if not args:
        print("usage: spiderman calendar exclude <8-char id from 'calendar calendars'>")
        return 1
    conf = load_conf()
    ex = set(conf.get("exclude", []))
    for db in find_caches():
        key = Path(db).parent.name
        if key.startswith(args[0]):
            ex.add(key)
            print(f"🚫 excluded {key[:8]}")
    conf["exclude"] = sorted(ex)
    save_conf(conf)
    return 0


def cmd_include(args):
    conf = load_conf()
    ex = [e for e in conf.get("exclude", []) if not e.startswith(args[0] if args else "")]
    conf["exclude"] = ex
    save_conf(conf)
    print("✅ included again")
    return 0


def cmd_events(args=()):
    events, err = fetch_events()
    if err:
        print(f"⚠️  {err}")
        return 1
    if not events:
        print(f"📅 No timed events in the next {LOOKAHEAD_H}h.")
        return 0
    print(f"📅 {len(events)} event(s) in the next {LOOKAHEAD_H}h:")
    for e in events:
        when = datetime.fromtimestamp(e["start"]).strftime("%a %d %b %H:%M")
        print(f"   {when}   {e['title']}")
    return 0


def cmd_sync(args=()):
    ensure_refresh_interval()   # keep Evolution polling every REFRESH_MINUTES
    request_refresh()           # nudge it before reading the cache
    st = pull()
    if "error" in st:
        print(f"⚠️  calendar sync: {st['error']}")
        return 1
    print(f"📅 calendar — {st['events']} upcoming event(s), +{st['added']} added")
    return 0


def cmd_show(args=()):
    conf = load_conf()
    print("📅 Calendar (via GNOME Online Accounts → Evolution)")
    print(f"   caches    : {len(find_caches())}")
    print(f"   lookahead : {LOOKAHEAD_H}h")
    print(f"   announces : {LEAD_MINUTES} min before each event")
    print(f"   all-day   : {'skipped' if SKIP_ALLDAY else 'included'}")
    if conf.get("exclude"):
        print(f"   excluded  : {', '.join(x[:8] for x in conf['exclude'])}")
    return 0


def cmd_seen(args):
    if not args:
        return 1
    seen = load_seen()
    seen[args[0]] = float(args[1]) if len(args) > 1 else datetime.now().timestamp()
    save_seen(seen)
    return 0


CMDS = {"calendars": cmd_calendars, "refresh": lambda a=(): (ensure_refresh_interval(), request_refresh(), print(f"🔄 asked Evolution to refresh (interval {REFRESH_MINUTES} min)"))[-1] or 0, "events": cmd_events, "sync": cmd_sync,
        "seen": cmd_seen, "show": cmd_show, "exclude": cmd_exclude,
        "include": cmd_include}


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in CMDS:
        print(__doc__)
        return 1
    return CMDS[sys.argv[1]](sys.argv[2:])


if __name__ == "__main__":
    sys.exit(main())
